spring.application.name=KnotFix

# Server Configuration
server.port=${SERVER_PORT:8090}
# Expose all web endpoints (including health and metrics)
management.endpoints.web.exposure.include=*
# Ensure the base path is explicitly set to /actuator
management.endpoints.web.base-path=/actuator


# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Session
server.servlet.session.timeout=30m

# Security Configuration
